### ISSUE TITLE
Suggested LLMs

### ISSUE THREAD

**Issue by DnVS97** [neuml/txtchat#1]
Hello, thanks for creating and sharing this github repository.

I was curious which LLMs you have experimented with and which one you would suggest for prompting?

Thanks in advance!

**Comment by davidmezzetti** [comment]
So far the best open models I've used are the FLAN-T5 models. I've had the best results with `flan-t5-xl` but pretty good results with `flan-t5-large`. The smaller variants can also work if you're willing to fine-tune.
