### ISSUE TITLE
install guide

### ISSUE THREAD

**Issue by dominikstein-ibm** [neuml/txtchat#2]
Hi David,

the installation guide is not complete. I managed to run RocketChat in docker compose and pip installed txtchat. 
What to do now? How do I integrate RocketChat to use txtchat? 
Where do I set these parameters?

> Set to server URL, this is default when running local
export URL=ws://localhost:3000/websocket
export USERNAME=<Rocket Chat User>
export PASSWORD=<Rocket Chat User Password>
YAML is loaded from Hugging Face Hub, can also reference local path
python -m txtchat.agent wikitalk.yml`

**Comment by davidmezzetti** [comment]
This issue was addressed in #3, closing.
