### ISSUE TITLE
Proccess killed

### ISSUE THREAD

**Issue by ZeadAlkhonein** [neuml/txtchat#5]
First thank you for this interesting project. 
anyhow i am trying to start the wikitalk.yml but it end up been killed with no traceback error. 
tried summary.yml it  worked  prefectly so i dunno how to fix it. and is it an error on my end ?

again thank you.
BR,

**Comment by davidmezzetti** [comment]
It seems like you don't have enough memory to run the default model.

If you download this file locally - https://huggingface.co/NeuML/txtchat-personas/raw/main/wikitalk.yml

Then change the model from `google/flan-t5-xl` to something else like `google/flan-t5-base` or `google/flan-t5-large`. You can then start the agent with that local file to see if the process starts up.

**Comment by davidmezzetti** [comment]
Looks like this has been resolved. Please re-open or create a new issue if this persists.
