### ISSUE TITLE
The path for the downloaded models

### ISSUE THREAD

**Issue by max-fry-apps** [neuml/txtchat#9]
Hello! Thanks for the amazing app.

Can you please help me to find where the downloaded models are located on my system?

I run: `python -m txtchat.agent wikitalk.yml`

**Comment by davidmezzetti** [comment]
Thanks.

The models are using the standard Hugging Face Transformers paths. The link below has information on where the models are cached.

https://huggingface.co/docs/transformers/installation#cache-setup

**Comment by max-fry-apps** [comment]
Thank you!
